Repository fluencelabs/aqua, pull requests merged in 2021-08, with the labels that each got.

#229 Return many values from a single function
  .github/workflows/release.yml
  aqua-src/ret.aqua
  backend/air/src/main/scala/aqua/backend/air/AirGen.scala
  backend/js/src/main/scala/aqua/backend/js/JavaScriptFunc.scala
  backend/ts/src/main/scala/aqua/backend/ts/TypeScriptFunc.scala
  build.sbt
  model/src/main/scala/aqua/model/ReturnModel.scala
  model/src/main/scala/aqua/model/transform/ResolveFunc.scala
  parser/src/main/scala/aqua/parser/expr/ArrowTypeExpr.scala
  parser/src/main/scala/aqua/parser/expr/CallArrowExpr.scala
  parser/src/main/scala/aqua/parser/expr/FuncExpr.scala
  parser/src/main/scala/aqua/parser/expr/ReturnExpr.scala
  parser/src/main/scala/aqua/parser/lexer/TypeToken.scala
  parser/src/test/scala/aqua/AquaSpec.scala
  parser/src/test/scala/aqua/parser/ArrowTypeExprSpec.scala
  parser/src/test/scala/aqua/parser/CallArrowSpec.scala
  parser/src/test/scala/aqua/parser/CoExprSpec.scala
  parser/src/test/scala/aqua/parser/FuncExprSpec.scala
  parser/src/test/scala/aqua/parser/ParExprSpec.scala
  parser/src/test/scala/aqua/parser/ReturnExprSpec.scala
  parser/src/test/scala/aqua/parser/lexer/TypeTokenSpec.scala
  semantics/src/main/scala/aqua/semantics/expr/CallArrowSem.scala
  semantics/src/main/scala/aqua/semantics/expr/FuncSem.scala
  semantics/src/main/scala/aqua/semantics/expr/ReturnSem.scala
  semantics/src/main/scala/aqua/semantics/rules/types/TypesState.scala
  types/src/main/scala/aqua/types/CompareTypes.scala
  types/src/main/scala/aqua/types/Type.scala
Labels: enhancement, syntax

#238 Multireturn bugfix
  aqua-src/ret.aqua
  model/src/main/scala/aqua/model/func/FuncCallable.scala
  model/src/main/scala/aqua/model/transform/ResolveFunc.scala
  semantics/src/main/scala/aqua/semantics/expr/FuncSem.scala
  types/src/main/scala/aqua/types/Type.scala
Labels: bug

#237 Crossprojects for JVM and JS platforms
  .jvmopts
  backend/.js/src/main/scala/aqua/backend/Version.scala
  backend/.jvm/src/main/scala/aqua/backend/Version.scala
  backend/air/src/main/scala/aqua/backend/air/AirGen.scala
  backend/js/src/main/scala/aqua/backend/js/JavaScriptFile.scala
  backend/ts/src/main/scala/aqua/backend/ts/TypeScriptFile.scala
  build.sbt
  cli/.js/src/main/scala/aqua/JsApp.scala
  cli/.jvm/src/main/scala/aqua/AppOps.scala
  cli/.jvm/src/main/scala/aqua/AquaCli.scala
  cli/.jvm/src/main/scala/aqua/AquaPathCompiler.scala
  cli/.jvm/src/main/scala/aqua/ErrorRendering.scala
  cli/.jvm/src/main/scala/aqua/Test.scala
  cli/.jvm/src/main/scala/aqua/files/AquaFileSources.scala
  cli/.jvm/src/main/scala/aqua/files/FileModuleId.scala
  cli/.jvm/src/test/aqua/test.aqua
  cli/.jvm/src/test/scala/SourcesSpec.scala
  cli/.jvm/src/test/scala/WriteFileSpec.scala
  cli/.jvm/src/test/test-dir/broken-import/broken.aqua
  cli/.jvm/src/test/test-dir/importNear.aqua
  cli/.jvm/src/test/test-dir/imports/import.aqua
  cli/.jvm/src/test/test-dir/index.aqua
  cli/.jvm/src/test/test-dir/path-test/importNear.aqua
  cli/.jvm/src/test/test-dir/path-test/index.aqua
  cli/src/main/scala/aqua/AquaIO.scala
  cli/src/main/scala/aqua/CustomLogFormatter.scala
  cli/src/main/scala/aqua/LogFormatter.scala
  cli/src/main/scala/aqua/LogLevel.scala
  cli/src/main/scala/aqua/files/AquaFilesIO.scala
  cli/src/main/scala/aqua/io/AquaFileError.scala
  linker/src/main/scala/aqua/linker/Linker.scala
  model/src/main/scala/aqua/model/AquaContext.scala
  model/src/main/scala/aqua/model/ValueModel.scala
  model/src/main/scala/aqua/model/func/FuncCallable.scala
  model/src/main/scala/aqua/model/func/raw/PathFinder.scala
  model/src/main/scala/aqua/model/func/raw/RawCursor.scala
  model/src/main/scala/aqua/model/topology/Topology.scala
  model/src/main/scala/aqua/model/transform/Transform.scala
  parser/src/test/scala/aqua/parser/FuncExprSpec.scala
  project/plugins.sbt
  semantics/src/main/scala/aqua/semantics/Semantics.scala
Labels: enhancement

#243 Updating compiler backends
  backend/air/src/main/scala/aqua/backend/air/AirBackend.scala
  backend/air/src/main/scala/aqua/backend/air/FuncAirGen.scala
  backend/js/src/main/scala/aqua/backend/js/JavaScriptBackend.scala
  backend/js/src/main/scala/aqua/backend/js/JavaScriptFile.scala
  backend/js/src/main/scala/aqua/backend/js/JavaScriptFunc.scala
  backend/src/main/scala/aqua/backend/Backend.scala
  backend/ts/src/main/scala/aqua/backend/ts/TypeScriptBackend.scala
  backend/ts/src/main/scala/aqua/backend/ts/TypeScriptFile.scala
  backend/ts/src/main/scala/aqua/backend/ts/TypeScriptFunc.scala
  backend/ts/src/main/scala/aqua/backend/ts/TypeScriptService.scala
  compiler/src/main/scala/aqua/compiler/AquaCompiler.scala
  model/src/main/scala/aqua/model/res/AquaRes.scala
  model/src/main/scala/aqua/model/res/FuncRes.scala
  model/src/main/scala/aqua/model/res/ServiceRes.scala
  model/src/main/scala/aqua/model/transform/Transform.scala
  model/test-kit/src/test/scala/aqua/model/transform/TransformSpec.scala
Labels: enhancement

#245 Module and Use expressions
  .gitignore
  .scalafmt.conf
  README.md
  build.sbt
  cli/src/main/scala/aqua/ErrorRendering.scala
  cli/src/main/scala/aqua/files/FileModuleId.scala
  compiler/src/main/scala/aqua/compiler/AquaCompiler.scala
  compiler/src/main/scala/aqua/compiler/AquaParser.scala
  compiler/src/main/scala/aqua/compiler/AquaProcessed.scala
  linker/src/main/scala/aqua/linker/AquaModule.scala
  linker/src/main/scala/aqua/linker/Linker.scala
  linker/src/main/scala/aqua/linker/Modules.scala
  linker/src/test/scala/aqua/linker/LinkerSpec.scala
  model/src/main/scala/aqua/model/AquaContext.scala
  model/transform/src/main/scala/aqua/model/transform/res/AquaRes.scala
  parser/src/main/scala/aqua/parser/Ast.scala
  parser/src/main/scala/aqua/parser/expr/AbilityIdExpr.scala
  parser/src/main/scala/aqua/parser/expr/CallArrowExpr.scala
  parser/src/main/scala/aqua/parser/head/ExportExpr.scala
  parser/src/main/scala/aqua/parser/head/FilenameExpr.scala
  parser/src/main/scala/aqua/parser/head/FromExpr.scala
  parser/src/main/scala/aqua/parser/head/HeadExpr.scala
  parser/src/main/scala/aqua/parser/head/HeaderExpr.scala
  parser/src/main/scala/aqua/parser/head/ImportExpr.scala
  parser/src/main/scala/aqua/parser/head/ImportFromExpr.scala
  parser/src/main/scala/aqua/parser/head/ModuleExpr.scala
  parser/src/main/scala/aqua/parser/head/UseExpr.scala
  parser/src/main/scala/aqua/parser/head/UseFromExpr.scala
  parser/src/main/scala/aqua/parser/lexer/Ability.scala
  parser/src/main/scala/aqua/parser/lexer/Name.scala
  parser/src/main/scala/aqua/parser/lexer/Token.scala
  parser/src/main/scala/aqua/parser/lexer/TypeToken.scala
  parser/src/main/scala/aqua/parser/lexer/Value.scala
  parser/src/main/scala/aqua/parser/lift/LiftParser.scala
  semantics/src/main/scala/aqua/semantics/SemanticError.scala
  semantics/src/main/scala/aqua/semantics/Semantics.scala
  semantics/src/main/scala/aqua/semantics/expr/CallArrowSem.scala
  semantics/src/main/scala/aqua/semantics/header/HeaderSem.scala
  semantics/src/main/scala/aqua/semantics/rules/ValuesAlgebra.scala
  semantics/src/main/scala/aqua/semantics/rules/abilities/AbilitiesAlgebra.scala
  semantics/src/main/scala/aqua/semantics/rules/abilities/AbilitiesInterpreter.scala
  semantics/src/main/scala/aqua/semantics/rules/abilities/AbilitiesState.scala
  semantics/src/main/scala/aqua/semantics/rules/abilities/AbilityOp.scala
  semantics/src/main/scala/aqua/semantics/rules/types/TypesState.scala
Labels: enhancement, syntax

#249 Imports bugfixes
  aqua-src/ret.aqua
  aqua/error.aqua
  aqua/service.aqua
  cli/.jvm/src/main/scala/aqua/Test.scala
  model/transform/src/main/scala/aqua/model/transform/res/AquaRes.scala
  parser/src/main/scala/aqua/parser/head/UseExpr.scala
  parser/src/main/scala/aqua/parser/lexer/Token.scala
  parser/src/test/scala/aqua/parser/AbilityIdExprSpec.scala
  parser/src/test/scala/aqua/parser/head/FromSpec.scala
  parser/src/test/scala/aqua/parser/head/ImportFromSpec.scala
  parser/src/test/scala/aqua/parser/head/ModuleSpec.scala
  semantics/src/main/scala/aqua/semantics/header/HeaderSem.scala
Labels: bug

#252 JS Backend: add missing single quote (')
  backend/js/src/main/scala/aqua/backend/js/JavaScriptFunc.scala
Labels: bug

#241 Support for the new (ap instruction
  backend/air/src/main/scala/aqua/backend/air/Air.scala
  backend/air/src/main/scala/aqua/backend/air/AirGen.scala
  build.sbt
  model/src/main/scala/aqua/model/ValueModel.scala
  model/src/main/scala/aqua/model/func/FuncCallable.scala
  model/src/main/scala/aqua/model/func/raw/FuncOp.scala
  model/src/main/scala/aqua/model/func/raw/FuncOps.scala
  model/src/main/scala/aqua/model/func/raw/RawTag.scala
  model/transform/src/main/scala/aqua/model/transform/TransformConfig.scala
  model/transform/src/main/scala/aqua/model/transform/funcop/ArgsProvider.scala
  model/transform/src/main/scala/aqua/model/transform/res/MakeRes.scala
  model/transform/src/main/scala/aqua/model/transform/res/ResolvedOp.scala
  semantics/src/main/scala/aqua/semantics/expr/PushToStreamSem.scala
Labels: enhancement

#258 Imports/exports fixes
  aqua-src/export.aqua
  aqua-src/gen/OneMore.aqua
  aqua-src/import.aqua
  build.sbt
  model/src/main/scala/aqua/model/AquaContext.scala
  parser/src/main/scala/aqua/parser/head/ModuleExpr.scala
  semantics/src/main/scala/aqua/semantics/header/HeaderSem.scala
  semantics/src/main/scala/aqua/semantics/rules/abilities/AbilitiesInterpreter.scala
  types/src/main/scala/aqua/types/Type.scala
Labels: bug
