Repository fluencelabs/aqua, pull requests merged in 2021-06, with the labels that each got.

#146 108 option type
  aqua-src/error.aqua
  backend/air/src/main/scala/aqua/backend/air/AirGen.scala
  backend/ts/src/main/scala/aqua/backend/ts/TypescriptFunc.scala
  build.sbt
  model/src/main/scala/aqua/model/func/body/FuncOps.scala
  model/src/main/scala/aqua/model/transform/ArgsProvider.scala
  parser/src/main/scala/aqua/parser/lexer/TypeToken.scala
  semantics/src/main/scala/aqua/semantics/expr/DeclareStreamSem.scala
  semantics/src/main/scala/aqua/semantics/expr/ForSem.scala
  semantics/src/main/scala/aqua/semantics/rules/types/TypesState.scala
  types/src/main/scala/aqua/types/Type.scala
  types/src/test/scala/aqua/types/TypeSpec.scala
Labels: enhancement, syntax

#149 Simple opt-as-an-array fix
  backend/air/src/main/scala/aqua/backend/air/AirGen.scala
  backend/ts/src/main/scala/aqua/backend/ts/TypescriptFunc.scala
  model/src/main/scala/aqua/model/transform/ArgsProvider.scala
  model/src/main/scala/aqua/model/transform/ErrorsCatcher.scala
  model/src/test/scala/aqua/model/Node.scala
Labels: bug

#152 Use file as an input
  cli/src/main/scala/aqua/AppOps.scala
  cli/src/main/scala/aqua/AquaCli.scala
  cli/src/main/scala/aqua/AquaCompiler.scala
  cli/src/main/scala/aqua/io/AquaFiles.scala
Labels: enhancement

#153 Support options for `via` clause in `on` expression
  aqua-src/error.aqua
  backend/air/src/main/scala/aqua/backend/air/Air.scala
  backend/air/src/main/scala/aqua/backend/air/AirGen.scala
  model/src/main/scala/aqua/model/func/body/FuncOps.scala
  model/src/main/scala/aqua/model/func/body/OpTag.scala
  model/src/main/scala/aqua/model/topology/Cursor.scala
  model/src/main/scala/aqua/model/topology/Topology.scala
  model/src/main/scala/aqua/model/transform/ArgsProvider.scala
  semantics/src/main/scala/aqua/semantics/expr/OnSem.scala
Labels: enhancement

#154 Fix: resolve function return name
  aqua-src/demo.aqua
  aqua/error.aqua
  build.sbt
  model/src/main/scala/aqua/model/func/FuncCallable.scala
  model/src/main/scala/aqua/model/transform/ResolveFunc.scala
Labels: bug

#155 AssignmentExpression
  aqua-src/demo.aqua
  backend/air/src/main/scala/aqua/backend/air/AirGen.scala
  build.sbt
  model/src/main/scala/aqua/model/ServiceModel.scala
  model/src/main/scala/aqua/model/func/FuncCallable.scala
  model/src/main/scala/aqua/model/func/body/FuncOp.scala
  model/src/main/scala/aqua/model/func/body/OpTag.scala
  model/src/main/scala/aqua/model/transform/Transform.scala
  parser/src/main/scala/aqua/parser/expr/ForExpr.scala
  parser/src/main/scala/aqua/parser/expr/FuncExpr.scala
  parser/src/main/scala/aqua/parser/expr/IfExpr.scala
  parser/src/main/scala/aqua/parser/expr/OnExpr.scala
  semantics/src/main/scala/aqua/semantics/ExprSem.scala
  semantics/src/main/scala/aqua/semantics/expr/AbilityIdSem.scala
  semantics/src/main/scala/aqua/semantics/expr/AssignmentSem.scala
  semantics/src/main/scala/aqua/semantics/expr/ServiceSem.scala
  semantics/src/main/scala/aqua/semantics/rules/abilities/AbilitiesAlgebra.scala
  semantics/src/main/scala/aqua/semantics/rules/abilities/AbilitiesInterpreter.scala
  semantics/src/main/scala/aqua/semantics/rules/abilities/AbilityOp.scala
Labels: enhancement, syntax

#156 Model refactoring to isolate imports, exports
  aqua-src/app.aqua
  aqua-src/chatApp.aqua
  aqua-src/demo.aqua
  aqua-src/service.aqua
  backend/ts/src/main/scala/aqua/backend/ts/TypescriptFile.scala
  cli/src/main/scala/aqua/AquaCli.scala
  cli/src/main/scala/aqua/AquaCompiler.scala
  cli/src/main/scala/aqua/io/AquaFiles.scala
  model/src/main/scala/aqua/model/AquaContext.scala
  model/src/main/scala/aqua/model/ConstantModel.scala
  model/src/main/scala/aqua/model/ScriptModel.scala
  model/src/main/scala/aqua/model/ServiceModel.scala
  model/src/main/scala/aqua/model/func/FuncCallable.scala
  semantics/src/main/scala/aqua/semantics/CompilerState.scala
  semantics/src/main/scala/aqua/semantics/SemanticError.scala
  semantics/src/main/scala/aqua/semantics/Semantics.scala
  semantics/src/main/scala/aqua/semantics/expr/AbilityIdSem.scala
  semantics/src/main/scala/aqua/semantics/expr/CallArrowSem.scala
  semantics/src/main/scala/aqua/semantics/expr/ConstantSem.scala
  semantics/src/main/scala/aqua/semantics/expr/ServiceSem.scala
  semantics/src/main/scala/aqua/semantics/rules/abilities/AbilitiesAlgebra.scala
  semantics/src/main/scala/aqua/semantics/rules/abilities/AbilitiesInterpreter.scala
  semantics/src/main/scala/aqua/semantics/rules/abilities/AbilitiesState.scala
  semantics/src/main/scala/aqua/semantics/rules/abilities/AbilityOp.scala
  semantics/src/main/scala/aqua/semantics/rules/names/NamesState.scala
  semantics/src/main/scala/aqua/semantics/rules/types/TypesState.scala
Labels: enhancement

#161 Javascript backend
  backend/js/src/main/scala/aqua/backend/js/JavaScriptFile.scala
  backend/js/src/main/scala/aqua/backend/js/JavaScriptFunc.scala
  build.sbt
  cli/src/main/scala/aqua/AppOps.scala
  cli/src/main/scala/aqua/AquaCli.scala
  cli/src/main/scala/aqua/AquaCompiler.scala
Labels: enhancement

#162 Introduce Catch expression
  aqua-src/demo.aqua
  aqua/app.aqua
  aqua/chatApp.aqua
  aqua/service.aqua
  build.sbt
  cli/src/main/scala/aqua/AquaCompiler.scala
  model/src/main/scala/aqua/model/AquaContext.scala
  model/src/main/scala/aqua/model/ValueModel.scala
  model/src/main/scala/aqua/model/func/FuncCallable.scala
  model/src/main/scala/aqua/model/func/body/OpTag.scala
  model/src/main/scala/aqua/model/transform/BodyConfig.scala
  model/src/main/scala/aqua/model/transform/ErrorsCatcher.scala
  parser/src/main/scala/aqua/parser/Expr.scala
  parser/src/main/scala/aqua/parser/expr/AbilityIdExpr.scala
  parser/src/main/scala/aqua/parser/expr/AliasExpr.scala
  parser/src/main/scala/aqua/parser/expr/ArrowTypeExpr.scala
  parser/src/main/scala/aqua/parser/expr/AssignmentExpr.scala
  parser/src/main/scala/aqua/parser/expr/CallArrowExpr.scala
  parser/src/main/scala/aqua/parser/expr/CatchExpr.scala
  parser/src/main/scala/aqua/parser/expr/ConstantExpr.scala
  parser/src/main/scala/aqua/parser/expr/DataStructExpr.scala
  parser/src/main/scala/aqua/parser/expr/DeclareStreamExpr.scala
  parser/src/main/scala/aqua/parser/expr/ElseOtherwiseExpr.scala
  parser/src/main/scala/aqua/parser/expr/FieldTypeExpr.scala
  parser/src/main/scala/aqua/parser/expr/ForExpr.scala
  parser/src/main/scala/aqua/parser/expr/FuncExpr.scala
  parser/src/main/scala/aqua/parser/expr/IfExpr.scala
  parser/src/main/scala/aqua/parser/expr/OnExpr.scala
  parser/src/main/scala/aqua/parser/expr/ParExpr.scala
  parser/src/main/scala/aqua/parser/expr/ReturnExpr.scala
  parser/src/main/scala/aqua/parser/expr/RootExpr.scala
  parser/src/main/scala/aqua/parser/expr/ServiceExpr.scala
  parser/src/main/scala/aqua/parser/expr/TryExpr.scala
  parser/src/main/scala/aqua/parser/lexer/Token.scala
  parser/src/main/scala/aqua/parser/lift/FileSpan.scala
  parser/src/main/scala/aqua/parser/lift/LiftParser.scala
  parser/src/main/scala/aqua/parser/lift/Span.scala
  parser/src/test/scala/aqua/parser/ElseOtherwiseExprSpec.scala
  parser/src/test/scala/aqua/parser/FuncExprSpec.scala
  parser/src/test/scala/aqua/parser/ParExprSpec.scala
  semantics/src/main/scala/aqua/semantics/CompilerState.scala
  semantics/src/main/scala/aqua/semantics/ExprSem.scala
  semantics/src/main/scala/aqua/semantics/Prog.scala
  semantics/src/main/scala/aqua/semantics/Semantics.scala
  semantics/src/main/scala/aqua/semantics/expr/CatchSem.scala
  semantics/src/main/scala/aqua/semantics/expr/ElseOtherwiseSem.scala
  semantics/src/main/scala/aqua/semantics/expr/ForSem.scala
  semantics/src/main/scala/aqua/semantics/expr/IfSem.scala
  semantics/src/main/scala/aqua/semantics/expr/TrySem.scala
Labels: enhancement, syntax

#172 157 multiline function definitions
  aqua-src/demo.aqua
  parser/src/main/scala/aqua/parser/expr/CallArrowExpr.scala
  parser/src/main/scala/aqua/parser/expr/FuncExpr.scala
  parser/src/main/scala/aqua/parser/lexer/Token.scala
  parser/src/main/scala/aqua/parser/lexer/TypeToken.scala
  parser/src/test/scala/aqua/parser/FuncExprSpec.scala
Labels: bug, enhancement

#177 Fixes missing par
  aqua-src/demo.aqua
  aqua-src/print.aqua
  aqua/builtin.aqua
  backend/air/src/main/scala/aqua/backend/air/AirGen.scala
  build.sbt
  model/src/main/scala/aqua/model/AquaContext.scala
  model/src/main/scala/aqua/model/Model.scala
  model/src/main/scala/aqua/model/ValueModel.scala
  model/src/main/scala/aqua/model/cursor/ChainCursor.scala
  model/src/main/scala/aqua/model/cursor/ChainZipper.scala
  model/src/main/scala/aqua/model/func/Call.scala
  model/src/main/scala/aqua/model/func/FuncCallable.scala
  model/src/main/scala/aqua/model/func/FuncModel.scala
  model/src/main/scala/aqua/model/func/raw/FuncOp.scala
  model/src/main/scala/aqua/model/func/raw/FuncOps.scala
  model/src/main/scala/aqua/model/func/raw/PathFinder.scala
  model/src/main/scala/aqua/model/func/raw/RawCursor.scala
  model/src/main/scala/aqua/model/func/raw/RawTag.scala
  model/src/main/scala/aqua/model/func/raw/ShowFuncOp.scala
  model/src/main/scala/aqua/model/func/resolved/MakeRes.scala
  model/src/main/scala/aqua/model/func/resolved/ResolvedOp.scala
  model/src/main/scala/aqua/model/topology/Cursor.scala
  model/src/main/scala/aqua/model/topology/Location.scala
  model/src/main/scala/aqua/model/topology/Topology.scala
  model/src/main/scala/aqua/model/transform/ArgsProvider.scala
  model/src/main/scala/aqua/model/transform/ErrorsCatcher.scala
  model/src/main/scala/aqua/model/transform/InitPeerCallable.scala
  model/src/main/scala/aqua/model/transform/ResolveFunc.scala
  model/src/main/scala/aqua/model/transform/Transform.scala
  parser/src/main/scala/aqua/parser/Expr.scala
  parser/src/test/scala/aqua/parser/FuncExprSpec.scala
  semantics/src/main/scala/aqua/semantics/Semantics.scala
  semantics/src/main/scala/aqua/semantics/expr/AbilityIdSem.scala
  semantics/src/main/scala/aqua/semantics/expr/AssignmentSem.scala
  semantics/src/main/scala/aqua/semantics/expr/CallArrowSem.scala
  semantics/src/main/scala/aqua/semantics/expr/CatchSem.scala
  semantics/src/main/scala/aqua/semantics/expr/ElseOtherwiseSem.scala
  semantics/src/main/scala/aqua/semantics/expr/ForSem.scala
  semantics/src/main/scala/aqua/semantics/expr/FuncSem.scala
  semantics/src/main/scala/aqua/semantics/expr/IfSem.scala
  semantics/src/main/scala/aqua/semantics/expr/OnSem.scala
  semantics/src/main/scala/aqua/semantics/expr/ParSem.scala
  semantics/src/main/scala/aqua/semantics/expr/TrySem.scala
  semantics/src/test/scala/aqua/semantics/SemanticsSpec.scala
  test-kit/src/main/scala/aqua/Node.scala
  test-kit/src/test/scala/aqua/model/topology/LocationSpec.scala
  test-kit/src/test/scala/aqua/model/topology/TopologySpec.scala
  test-kit/src/test/scala/aqua/model/transform/TransformSpec.scala
  types/src/main/scala/aqua/types/Type.scala
Labels: bug

#181 Co expression
  backend/air/src/main/scala/aqua/backend/air/AirGen.scala
  build.sbt
  model/src/main/scala/aqua/model/func/raw/FuncOp.scala
  model/src/main/scala/aqua/model/func/raw/FuncOps.scala
  model/src/main/scala/aqua/model/func/raw/PathFinder.scala
  model/src/main/scala/aqua/model/func/raw/RawCursor.scala
  model/src/main/scala/aqua/model/func/raw/RawTag.scala
  model/src/main/scala/aqua/model/topology/Topology.scala
  parser/src/main/scala/aqua/parser/expr/CoExpr.scala
  parser/src/main/scala/aqua/parser/expr/FuncExpr.scala
  parser/src/main/scala/aqua/parser/expr/IfExpr.scala
  parser/src/main/scala/aqua/parser/expr/OnExpr.scala
  parser/src/main/scala/aqua/parser/lexer/Token.scala
  semantics/src/main/scala/aqua/semantics/ExprSem.scala
  semantics/src/main/scala/aqua/semantics/expr/CoSem.scala
Labels: enhancement, syntax
