Repository fluencelabs/aqua, pull requests merged in 2021-09, with the labels that each got.

#267 JS: fix invalid imports (fixes #263)
  backend/js/src/main/scala/aqua/backend/js/JavaScriptFile.scala
Labels: bug

#260 Upper cased constants
  .github/workflows/test_branch.yml
  .jvmopts
  aqua-src/export.aqua
  aqua-src/import.aqua
  aqua-src/ret.aqua
  backend/air/src/main/scala/aqua/backend/air/AirGen.scala
  build.sbt
  cli/.jvm/src/main/scala/aqua/Test.scala
  cli/src/main/scala/aqua/AppOps.scala
  model/src/main/scala/aqua/model/AquaContext.scala
  model/src/main/scala/aqua/model/ValueModel.scala
  model/transform/src/main/scala/aqua/model/transform/TransformConfig.scala
  parser/src/main/scala/aqua/parser/expr/ConstantExpr.scala
  parser/src/main/scala/aqua/parser/head/FromExpr.scala
  parser/src/main/scala/aqua/parser/head/ImportExpr.scala
  parser/src/main/scala/aqua/parser/head/ImportFromExpr.scala
  parser/src/main/scala/aqua/parser/head/UseExpr.scala
  parser/src/main/scala/aqua/parser/head/UseFromExpr.scala
  parser/src/main/scala/aqua/parser/lexer/Name.scala
  parser/src/main/scala/aqua/parser/lexer/Token.scala
  parser/src/test/scala/aqua/parser/AssignmentExprSpec.scala
  parser/src/test/scala/aqua/parser/head/FromSpec.scala
  parser/src/test/scala/aqua/parser/head/UseSpec.scala
  parser/src/test/scala/aqua/parser/lexer/TokenSpec.scala
  parser/src/test/scala/aqua/parser/lexer/VarLambdaSpec.scala
  semantics/src/main/scala/aqua/semantics/CompilerState.scala
  semantics/src/main/scala/aqua/semantics/header/HeaderSem.scala
  semantics/src/main/scala/aqua/semantics/rules/ValuesAlgebra.scala
Labels: syntax

#295 Readme updates
  README.md
  cli/src/main/scala/aqua/AppOps.scala
  cli/src/main/scala/aqua/AquaCli.scala
  npm/readme.md
Labels: documentation
