Repository fluencelabs/aqua, pull requests merged in 2022-06, with the labels that each got.

#516 Go-to definitions location between files
  build.sbt
  cli/.js/src/main/scala/aqua/FuncCompiler.scala
  cli/src/main/scala/aqua/AquaPathCompiler.scala
  compiler/src/main/scala/aqua/compiler/AquaCompiler.scala
  compiler/src/main/scala/aqua/compiler/AquaParser.scala
  compiler/src/main/scala/aqua/compiler/CompilerAPI.scala
  compiler/src/test/scala/aqua/compiler/AquaCompilerSpec.scala
  language-server-api/src/main/scala/aqua/lsp/AquaLSP.scala
  language-server-npm/aqua-lsp-api.d.ts
  model/raw/src/main/scala/aqua/raw/RawContext.scala
  model/src/main/scala/aqua/model/AquaContext.scala
  parser/src/main/scala/aqua/parser/lift/FileSpan.scala
  semantics/src/main/scala/aqua/semantics/CompilerState.scala
  semantics/src/main/scala/aqua/semantics/Semantics.scala
  semantics/src/main/scala/aqua/semantics/header/HeaderHandler.scala
  semantics/src/main/scala/aqua/semantics/header/HeaderSem.scala
  semantics/src/main/scala/aqua/semantics/header/Picker.scala
  semantics/src/main/scala/aqua/semantics/lsp/LspContext.scala
  semantics/src/main/scala/aqua/semantics/rules/abilities/AbilitiesInterpreter.scala
  semantics/src/test/scala/aqua/semantics/SemanticsSpec.scala
Labels: lsp, vscode

#518 Fix arguments renaming in functions
  model/raw/src/main/scala/aqua/raw/value/ValueRaw.scala
Labels: bug

#519 LNG-59 Fix lambda resolving
  model/src/main/scala/aqua/model/ValueModel.scala
Labels: bug

#529 LNG-67 Find JSON service in imported files for `aqua run`
  cli/.js/src/main/scala/aqua/FuncCompiler.scala
Labels: cli

#528 Fixes LNG-63: introduced ShadowRaw
  aqua-src/antithesis.aqua
  cli/.jvm/src/main/scala/aqua/Test.scala
  model/inline/src/main/scala/aqua/model/inline/RawValueInliner.scala
  model/raw/src/main/scala/aqua/raw/value/ValueRaw.scala
  semantics/src/main/scala/aqua/semantics/expr/func/ArrowSem.scala
  semantics/src/main/scala/aqua/semantics/expr/func/AssignmentSem.scala
  semantics/src/main/scala/aqua/semantics/expr/func/ForSem.scala
  semantics/src/main/scala/aqua/semantics/rules/names/NamesAlgebra.scala
  semantics/src/main/scala/aqua/semantics/rules/names/NamesInterpreter.scala
  semantics/src/main/scala/aqua/semantics/rules/names/NamesState.scala
Labels: bug
